config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :characters

  devise_scope :user do
    get "/login", to: "devise/sessions#new"
    delete "/logout", to: 'devise/sessions#destroy', as: :destroy_user_session
    root to: "devise/sessions#new"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :profession, optional: true

  validates :name, presence: true
  validates :gender_identity, presence: true
  validates :date_of_birth, presence: true

  def deceased?
    !alive
  end

  def present_status
    alive? ? "Alive" : "Deceased"
  end
end

app/models/profession.rb
require 'csv'

class Profession < ApplicationRecord
  has_many :characters

  def self.import(file_path: Rails.root.join('db','data','professions.csv'))
    raise IOError, 'No Professions File Found' unless File.exist?(file_path)
    CSV::Converters[:blank_to_nil] = ->(field) { field.blank? ? nil : field }
    CSV::Converters[:strip] = ->(field) { field.strip rescue field }

    CSV.foreach(file_path, headers: true, header_converters: :symbol, encoding: 'ISO-8859-1', converters: %i[strip blank_to_nil]) do |row|
      profession = Profession.find_or_create_by(name: row[:name])
      attributes_hash = { description: row[:discription]}
      profession.update(attributes_hash)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :characters

  devise :omniauthable, omniauth_providers: %i[auth0]

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.nickname = auth.info.nickname
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource_or_scope)
    characters_path
  end

  def after_sign_out_path_for(resource_or_scope)
    login_path
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :character_load, only: [:show, :edit, :update]

  def index
    @characters = current_user.characters
  end

  def new
    @character = Character.new
  end

  def create
    @character = current_user.characters.build(character_params)

    if @character.save
      redirect_to characters_path, notice: "Character was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @character.update(character_params)
      redirect_to characters_path, notice: "Character was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @character = current_user.characters.find(params[:id])

    @character.destroy

    redirect_to characters_path, notice: "Character was successfully destroyed."
  end

  def character_load
    @character = current_user.characters.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:user, :name, :gender_identity, :date_of_birth, :profession_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token

  def auth0
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user, :event => :authentication
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/_character.html.erb
<div class="columns is-centered">
  <div class="column is-one-quarter">
    <%= character.name %>
  </div>
  <div class="column is-one-quarter">
    <%= character.present_status %>
  </div>
  <div class="column is-half is-narrow">
    <%= link_to "View", character_path(character), class: "button is-primary is-small is-info" %>
    <%= link_to "Edit", edit_character_path(character), class: "button is-primary is-small" %>
    <%= link_to "Delete", character_path(character), class: "button is-primary is-small is-danger", data: {turbo_method: :delete} %>
  </div>
</div>

app/views/characters/_errors.html.erb
<% if character.errors.any? %>
  <div class="message is-danger has-text-danger">
    <% character.errors.full_messages.each do |message| %>
      <li class="field-with-errors"><%= message %></li>
    <% end %>
  </div>
<% end %>

app/views/characters/_form.html.erb
<%= form_with model: character, html: { class: "character form" } do |form| %>

  <%= render partial: 'errors', locals: { character: character } %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender_identity %>
    <%= form.text_field :gender_identity %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_field  :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :profession_id %>
    <%= form.collection_select :profession_id, Profession.order(:name), :id, :name, {include_blank: 'Select a profession'} %>
  </div>

  <%= form.submit submit_text, class: "button is-rounded is-primary" %>
<% end %>

app/views/characters/edit.html.erb
<div class="columns">
  <div class="column"><%= link_to sanitize("&larr; Back to characters"), characters_path %></div>
</div>

<%= render partial: 'form', locals: { character: @character, submit_text: "Update Character" } %>

app/views/characters/index.html.erb
<div class="columns">
  <div class="column">
    <h1 class="is-size-3">Characters Index</h1>
  </div>
  <div class="column">
    <%= link_to "New character", new_character_path, class: "button is-primary" %>
  </div>
</div>

<div class="columns is-centered">
  <div class="column is-one-quarter">
    <h2 class="is-size-4">Name</h2>
  </div>
  <div class="column is-one-quarter">
    <h2 class="is-size-4">Status</h2>
  </div>
  <div class="column is-half is-narrow">
    <h2 class="is-size-4">Actions</h2>
  </div>
</div>

<%= render partial: 'character', collection: @characters, as: :character %>

app/views/characters/new.html.erb
<div class="columns">
  <div class="column"><%= link_to sanitize("&larr; Back to characters"), characters_path %></div>
</div>

<%= render partial: 'form', locals: { character: @character, submit_text: "Create Character" } %>

app/views/characters/show.html.erb
<div class="columns">
  <div class="column"><%= link_to sanitize("&larr; Back to characters"), characters_path %></div>
</div>

<div class="content">
  <p>Name: <%= @character.name %></p>
  <p>Status: <%= @character.present_status %></p>
  <p>Gender: <%= @character.gender_identity %></p>
  <p>Profession: <%= @character.profession&.name %></p>
  <p>Birthday: <%= I18n.l(@character.date_of_birth, format: :as_date) %></p>
  <% if @character.deceased? %>
    <p>Birthday: <%= I18n.l(@character.deceased_at, format: :as_date) %></p>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar has-background-primary-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src=<%= asset_path("brand.png") %> alt='Demo'>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        This
      </a>
      <a class="navbar-item">
        That
      </a>
      <a class="navbar-item">
        Other thing
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if current_user %>
            <%= button_to('Logout', destroy_user_session_path, 'data-turbo': 'false', method: :delete, class: 'button is-danger') %>
          <% else %>
            <%= button_to "Log in", user_auth0_omniauth_authorize_path, 'data-turbo': 'false', method: :post, class: 'button is-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% if notice.present? %>
  <p class="notification is-success"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="notification"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoQuest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/notifications' %>

    <div class="container has-background-info-light">
      <%= yield %>
    </div>
  </body>
</html>